# Generated by Django 5.2.11 on 2026-04-07 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Autoevaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel_desempeño", models.CharField(max_length=100)),
                ("actividad_real", models.IntegerField(blank=True, null=True)),
                ("actividad_simulada", models.IntegerField(blank=True, null=True)),
                ("hora_inicio", models.TimeField()),
                ("hora_final", models.TimeField()),
                ("fecha", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_lugar", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Procedimientos",
            fields=[
                (
                    "id_procedimientos",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nombre_p", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BorradorRetroalimentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel_desempeño", models.IntegerField()),
                ("observaciones", models.TextField()),
                (
                    "autoevaluacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.autoevaluacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cedula_estudiante", models.IntegerField(unique=True)),
                ("nombre_1", models.CharField(max_length=100)),
                ("nombre_2", models.CharField(blank=True, max_length=100, null=True)),
                ("apellido_1", models.CharField(max_length=100)),
                ("apellido_2", models.CharField(blank=True, max_length=100, null=True)),
                ("semestre", models.IntegerField()),
                ("estado", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BorradorAutoevaluacion",
            fields=[
                (
                    "id_borrador_autoevaluacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre_procedimiento", models.CharField(max_length=255)),
                ("procedimiento", models.IntegerField()),
                ("id_procedimientos", models.IntegerField()),
                ("id_lugar", models.IntegerField()),
                ("nivel_desempeño", models.IntegerField()),
                ("actividad", models.BooleanField()),
                ("cedula_profesor", models.IntegerField()),
                ("hora_inicio", models.TimeField()),
                ("hora_final", models.TimeField()),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "estudiante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.estudiante"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="autoevaluacion",
            name="estudiante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.estudiante"
            ),
        ),
        migrations.AddField(
            model_name="autoevaluacion",
            name="lugar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.lugar"
            ),
        ),
        migrations.CreateModel(
            name="ProcedimientoAutoevaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedimiento", models.IntegerField()),
                (
                    "autoevaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.autoevaluacion",
                    ),
                ),
                (
                    "procedimiento_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.procedimientos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpcionProcedimientos",
            fields=[
                (
                    "id_opcion_procedimientos",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nombre_op", models.CharField(max_length=255)),
                (
                    "id_procedimientos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.procedimientos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cedula_profesor", models.IntegerField(unique=True)),
                ("nombre_1", models.CharField(max_length=100)),
                ("nombre_2", models.CharField(blank=True, max_length=100, null=True)),
                ("apellido_1", models.CharField(max_length=100)),
                ("apellido_2", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="autoevaluacion",
            name="profesor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.profesor"
            ),
        ),
        migrations.CreateModel(
            name="Retroalimentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel_desempeño", models.CharField(max_length=100)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "autoevaluacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.autoevaluacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubOpcionProcedimientos",
            fields=[
                (
                    "id_sub_opcion_procedimientos",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nombre_sop", models.CharField(max_length=255)),
                (
                    "id_opcion_procedimientos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.opcionprocedimientos",
                    ),
                ),
            ],
        ),
    ]
