# Generated by Django 5.2.11 on 2026-03-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigo_grupo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lugar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id_procedimientos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_p', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('cedula_profesor', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(max_length=100, null=True)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_roles', models.IntegerField(choices=[(1, 'Director del programa'), (2, 'Coordinador de Prácticas e Internado'), (3, 'Coordinador de curso'), (4, 'Profesor'), (5, 'Estudiante')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula_estudiante', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(max_length=100, null=True)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('semestre', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('codigo_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupo')),
                ('id_roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionProcedimientos',
            fields=[
                ('id_opcion_procedimientos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_op', models.CharField(max_length=255)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procedimientos')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='cedula_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profesor'),
        ),
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('id_autoevaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('actividad_real', models.IntegerField(null=True)),
                ('actividad_simulada', models.IntegerField(null=True)),
                ('cedula_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
                ('id_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lugar')),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procedimientos')),
                ('cedula_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='profesor',
            name='id_roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles'),
        ),
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('id_roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles')),
            ],
        ),
        migrations.CreateModel(
            name='SubOpcionProcedimientos',
            fields=[
                ('id_sub_opcion_procedimientos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sop', models.CharField(max_length=255)),
                ('id_opcion_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.opcionprocedimientos')),
            ],
        ),
    ]
