# Generated by Django 5.2.11 on 2026-03-04 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaClinica',
            fields=[
                ('id_comp_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel_esperado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinadorPracticas',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(max_length=100, null=True)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CursoClinico',
            fields=[
                ('id_curso_clinico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorPrograma',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(max_length=100, null=True)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionDocente',
            fields=[
                ('id_evalu_docente', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.FloatField()),
                ('nivel_dreyfus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_roles', models.IntegerField(choices=[(1, 'Director del programa'), (2, 'Coordinador de Prácticas e Internado'), (3, 'Coordinador de curso'), (4, 'Profesor'), (5, 'Estudiante')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinadorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(max_length=100, null=True)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coordinadorpracticas')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_grupo', models.IntegerField(unique=True)),
                ('semestre', models.IntegerField()),
                ('id_curso_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursoclinico')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cod_estudiante', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cedula_estu', models.IntegerField(unique=True)),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(max_length=100, null=True)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.IntegerField(unique=True)),
                ('semestre', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupo')),
                ('id_roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEvaluacion',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateField(auto_now_add=True)),
                ('usuario_editor', models.CharField(max_length=100)),
                ('detalles', models.TextField()),
                ('id_evalu_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.evaluaciondocente')),
            ],
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id_practica', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coordinadorpracticas')),
                ('id_curso_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursoclinico')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimientoClinico',
            fields=[
                ('id_proce_clinico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('id_comp_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.competenciaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimientoRealizado',
            fields=[
                ('id_proce_realizado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('id_practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.practica')),
                ('id_proce_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procedimientoclinico')),
            ],
        ),
        migrations.AddField(
            model_name='evaluaciondocente',
            name='id_proce_realizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procedimientorealizado'),
        ),
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('id_autoevaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_percibido', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comentarios', models.TextField()),
                ('id_proce_realizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procedimientorealizado')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('cedula_profesor', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(max_length=100, null=True)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coordinadorcurso')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='cedula_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profesor'),
        ),
        migrations.AddField(
            model_name='evaluaciondocente',
            name='cedula_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profesor'),
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('cod_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id_retroalimentacion', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('cedula_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profesor')),
                ('id_evalu_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.evaluaciondocente')),
            ],
        ),
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('id_roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles')),
            ],
        ),
        migrations.AddField(
            model_name='coordinadorpracticas',
            name='id_roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles'),
        ),
    ]
