# Generated by Django 5.2.11 on 2026-03-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinadorcurso',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='coordinadorpracticas',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='directorprograma',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
