# Generated by Django 5.2.11 on 2026-04-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="procedimientoautoevaluacion",
            old_name="procedimiento_ref",
            new_name="procedimientos",
        ),
    ]
