# Generated by Django 5.2.11 on 2026-03-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='email',
        ),
    ]
