# Generated by Django 5.2.11 on 2026-03-13 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoevaluacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='hora_final',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
