# Generated by Django 5.2.11 on 2026-04-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0002_rename_procedimiento_ref_procedimientoautoevaluacion_procedimientos",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borradorautoevaluacion",
            name="id_borrador_autoevaluacion",
        ),
        migrations.AddField(
            model_name="borradorautoevaluacion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
