# Generated by Django 5.2.11 on 2026-03-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_username_login_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='username',
        ),
    ]
