# Generated by Django 5.2.11 on 2026-03-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_autoevaluacion_fecha_autoevaluacion_hora_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoevaluacion',
            name='id_procedimientos',
        ),
        migrations.CreateModel(
            name='ProcedimientoAutoevaluacion',
            fields=[
                ('id_procedimiento_autoevaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_autoevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.autoevaluacion')),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procedimientos')),
            ],
        ),
    ]
