# Generated by Django 5.2.11 on 2026-03-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_coordinadorcurso_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinadorcurso',
            name='id_roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.roles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directorprograma',
            name='id_roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.roles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='id_roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.roles'),
            preserve_default=False,
        ),
    ]
