# Generated by Django 5.2.11 on 2026-03-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_email_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
