# Generated by Django 5.2.11 on 2026-03-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_autoevaluacion_id_procedimientos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimientoautoevaluacion',
            name='procedimiento',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
