# Generated by Django 5.2.11 on 2026-04-09 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0003_remove_borradorautoevaluacion_id_borrador_autoevaluacion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="curso",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profesor",
            name="estado",
            field=models.BooleanField(default=False),
        ),
    ]
