# Generated by Django 5.2.11 on 2026-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coordinadorcurso_id_roles_directorprograma_id_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuario',
            name='id_dat_user',
        ),
        migrations.AddField(
            model_name='datosusuario',
            name='cedula',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
