# Generated by Django 5.2.11 on 2026-03-06 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_datosusuario_id_dat_user_datosusuario_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='id_cur_cli',
        ),
        migrations.RemoveField(
            model_name='practica',
            name='id_cur_cli',
        ),
        migrations.AddField(
            model_name='cursoclinico',
            name='id_practica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.practica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practica',
            name='id_grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.grupo'),
            preserve_default=False,
        ),
    ]
