# Generated by Django 5.2.11 on 2026-03-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_procedimientoautoevaluacion_procedimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='codigo_grupo',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='nivel_dreyfus',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
