# Generated by Django 5.2.11 on 2026-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_profesor_curso_profesor_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profesor",
            name="estado",
            field=models.BooleanField(default=True),
        ),
    ]
