# Generated by Django 5.2.11 on 2026-03-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profesor_login_rol_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='login',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_rol', to='app.login'),
            preserve_default=False,
        ),
    ]
