# Generated by Django 5.2.11 on 2026-03-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_grupo_id_cur_cli_remove_practica_id_cur_cli_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoclinico',
            name='id_practica',
        ),
        migrations.CreateModel(
            name='PracticaCursoClinico',
            fields=[
                ('id_prac_cli', models.AutoField(primary_key=True, serialize=False)),
                ('id_cur_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursoclinico')),
                ('id_practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.practica')),
            ],
        ),
    ]
