# Generated by Django 5.2.11 on 2026-03-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_estudiante_codigo_grupo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoevaluacion',
            old_name='nivel_dreyfus',
            new_name='nivel_desempeño',
        ),
    ]
