# Generated by Django 5.2.11 on 2026-03-16 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_nivel_dreyfus_autoevaluacion_nivel_desempeño'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroAlimentacion',
            fields=[
                ('id_retroalimentacion', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_desempeño', models.CharField(max_length=100)),
                ('detalles', models.TextField(null=True)),
                ('id_autoevaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.autoevaluacion')),
            ],
        ),
    ]
