# Generated by Django 5.2.11 on 2026-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profesor_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DIC_PROGRAMA', 'Director del programa'), ('COORD_PRAC', 'Coordinador de Prácticas e Internado'), ('COORD_CURSO', 'Coordinador de curso'), ('PROFESOR', 'Profesor')], default='ESTUDIANTE', max_length=100),
        ),
    ]
