# Generated by Django 5.2.11 on 2026-03-17 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_retroalimentacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retroalimentacion',
            old_name='detalles',
            new_name='oberservaciones',
        ),
        migrations.AddField(
            model_name='retroalimentacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
