# Generated by Django 5.2.11 on 2026-03-02 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_login_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.login'),
        ),
    ]
