# Generated by Django 5.2.11 on 2026-03-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_detalles_retroalimentacion_oberservaciones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retroalimentacion',
            old_name='oberservaciones',
            new_name='observaciones',
        ),
    ]
