# Generated by Django 5.2.11 on 2026-03-03 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profesor_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='rol',
            field=models.CharField(choices=[('DIC_PROGRAMA', 'Director del programa'), ('COORD_PRAC', 'Coordinador de Prácticas e Internado'), ('COORD_CURSO', 'Coordinador de curso'), ('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=100),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.login')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profesor')),
            ],
        ),
    ]
