# Generated by Django 5.2.11 on 2026-03-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_oberservaciones_retroalimentacion_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorAutoevaluacion',
            fields=[
                ('id_borrador_autoevaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_procedimiento', models.CharField(max_length=255)),
                ('id_lugar', models.IntegerField()),
                ('nivel_desempeño', models.IntegerField()),
                ('actividad', models.BooleanField()),
                ('cedula_profesor', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('fecha', models.DateField()),
                ('cedula_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
            ],
        ),
    ]
