# Generated by Django 5.2.11 on 2026-03-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_borradorautoevaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='borradorautoevaluacion',
            name='id_procedimiento',
            field=models.IntegerField(default=14000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borradorautoevaluacion',
            name='procedimiento',
            field=models.IntegerField(default=14000),
            preserve_default=False,
        ),
    ]
