# Generated by Django 5.2.11 on 2026-03-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_borradorautoevaluacion_id_procedimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borradorautoevaluacion',
            old_name='id_procedimiento',
            new_name='id_procedimientos',
        ),
    ]
