# Generated by Django 5.2.11 on 2026-03-17 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_id_procedimiento_borradorautoevaluacion_id_procedimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorRetroalimentacion',
            fields=[
                ('id_borrador_retroalimentacion', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_desempeño', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('id_retroalimentacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.retroalimentacion')),
            ],
        ),
    ]
