# Generated by Django 5.2.11 on 2026-03-17 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_borradorretroalimentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borradorretroalimentacion',
            name='id_retroalimentacion',
        ),
        migrations.AddField(
            model_name='borradorretroalimentacion',
            name='id_autoevaluacion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.autoevaluacion'),
            preserve_default=False,
        ),
    ]
