# Generated by Django 5.2.11 on 2026-03-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_borradorretroalimentacion_id_retroalimentacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoevaluacion",
            name="fecha",
            field=models.DateField(auto_now_add=True),
        ),
    ]
