# Generated by Django 5.2.11 on 2026-03-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_autoevaluacion_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borradorautoevaluacion",
            name="fecha",
            field=models.DateField(auto_now_add=True),
        ),
    ]
