# Generated by Django 5.2.11 on 2026-04-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_borradorautoevaluacion_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="estado",
            field=models.BooleanField(default=False),
        ),
    ]
